routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Admin\Sorteo\IndexSorteo;
use App\Http\Livewire\Admin\Aspirante\ListAspirante;
use App\Http\Livewire\Admin\SorteosGanadores;

Route::redirect('/','/admin/sorteo');
Route::view('dashboard', 'admin.dashboard')->name('admin.dashboard');
Route::view('profile', "admin.profile.account")->name('admin.profile.account');
Route::view('grilla', 'admin.import-grilla')->name('admin.grilla');

Route::view('sorteo', 'admin.sorteo')->name('admin.sorteo');

Route::view('sorteos', 'admin.sorteo.list-sorteo')->name('admin.sorteos');

Route::view('ganador/{id}', 'admin.ganador')->name('admin.ganador');

$routes = ['articles', 'pages', 'menu', 'slider', 'users'];

foreach ($routes as $route) {
  Route::view($route, 'admin.'.$route.'.index')->name('admin.'.$route.'.index');
  Route::view($route.'/create', 'admin.'.$route.'.create')->name('admin.'.$route.'.create');
  Route::view($route.'/edit/{id}', 'admin.'.$route.'.edit')->name('admin.'.$route.'.edit');
}

routes/web.php
<?php

use App\Models\Aspirante;
use App\Http\Livewire\Front\Articles;
use App\Http\Livewire\Front\PageShow;
use Illuminate\Support\Facades\Route;
use App\Http\Livewire\Front\ArticlesShow;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/','/admin/sorteo');
// Route::get('/', Home::class)->name('home');
Route::get('/noticias', Articles::class)->name('articles');
Route::get('/noticias/{article}', ArticlesShow::class)->name('articles.show');
Route::get('/pagina/{page}', PageShow::class)->name('pages.show');



Auth::routes();

app/Models/Menu.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Menu extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'published',
        'link',
        'position',
        'icon',
        'to_home'
    ];

    public function pages(){
        return $this->hasMany(Page::class);
    }
}

app/Http/Livewire/Admin/Menu/EditMenu.php
<?php

namespace App\Http\Livewire\Admin\Menu;

use App\Models\Menu;
use Livewire\Component;

class EditMenu extends Component
{

    public $menu;
    public $targets;
    public $has_pages;

    protected $rules = [
        'menu.title'    => 'required',
        'menu.position' => 'required|numeric',
        'menu.to_home'  => 'nullable',
        'menu.link'     => 'nullable',
        'menu.icon'     => 'nullable',
        'menu.target'   => 'nullable',
    ];

    public function mount(Menu $menu){
        $this->menu = $menu;
        $this->has_pages = $menu->pages()->exists();
        $this->targets = [
            '_self' => 'En la misma ventana',
            '_blank' => 'En una ventana nueva',
        ];
    }
    
    public function save_menu(){
        $this->validate();
        $this->menu->save();

        $this->toast('Menu Actualizado');
    }

    public function toggle_status(){
        $this->menu->update([
            'published' => !$this->menu->published
        ]);
    }

    public function delete_menu(){
        $this->menu->delete();
        return redirect()->route('admin.menu.index');
    }

    public function render(){
        return view('livewire.admin.menu.edit-menu');
    }

    public  function toast($title, $icon = 'success'){
        $this->dispatchBrowserEvent('swal', [
            'title' => $title,
            'timer'=>2000,
            'icon'=> $icon,
            'toast'=>true,
            'position'=>'top-right',
            'showConfirmButton' =>  false,
        ]);
      }
}

app/Http/Livewire/Admin/Menu/ListMenu.php
<?php

namespace App\Http\Livewire\Admin\Menu;

use App\Models\Menu;
use Livewire\Component;
use Livewire\WithPagination;

class ListMenu extends Component
{
    use WithPagination;
    protected $paginationTheme = 'bootstrap';
    
    public function render(){

        $menus = Menu::orderBy('title')
            ->withCount('pages')
            ->paginate();
        return view('livewire.admin.menu.list-menu',[
            'menus' => $menus
        ]);
    }
}

app/Http/Livewire/Admin/Menu/NewMenu.php
<?php

namespace App\Http\Livewire\Admin\Menu;

use App\Models\Menu;
use Livewire\Component;

class NewMenu extends Component
{
    public $menu;
    public $targets;

    protected $rules = [
        'menu.title'    => 'required',
        'menu.position' => 'required|numeric',
        'menu.to_home'  => 'nullable',
        'menu.link'     => 'nullable',
        'menu.icon'     => 'nullable',
        'menu.target'   => 'nullable',
    ];

    public function mount(){
        $this->menu = new Menu();
        $this->menu->target = '_self';
        $this->targets = [
            '_self' => 'En la misma ventana',
            '_blank' => 'En una ventana nueva',
        ];

    }
    
    public function save_menu(){
        $this->validate();

        $this->menu->published = false;
        $this->menu->to_home = $this->menu->to_home ? true : false;
        $this->menu->save();
        
        return redirect()->route('admin.menu.edit', $this->menu->id);
    }

    public function render(){
        return view('livewire.admin.menu.new-menu');
    }
}

app/Http/Livewire/Front/Menu.php
<?php

namespace App\Http\Livewire\Front;

use Livewire\Component;

class Menu extends Component
{
    public function render()
    {
        return view('livewire.front.menu');
    }
}

app/Http/Livewire/Front/Menu/DynamicMenu.php
<?php

namespace App\Http\Livewire\Front\Menu;

use App\Models\Menu;
use Livewire\Component;

class DynamicMenu extends Component
{
    public function render(){

        $menus = Menu::whereToHome(false)
            ->with('pages')
            ->orderBy('position')
            ->get();

        return view('livewire.front.menu.dynamic-menu', [
            'menus' => $menus
        ]);
    }
}

resources/views/livewire/admin/menu/edit-menu.blade.php
<div class="row">
    <div class="col-md-9">
        <x-admin.card title="Datos del Menu">
            @include('livewire.admin.menu.form')
        </x-admin.card>
    </div>
    <div class="col-md-3">
        <x-admin.card title="Opciones">
            <x-admin.save-btn event="save_menu" updatedtext="{{ $menu->updated_at->format('d/m/y H:i:s') }}" newLine=true />
            <hr>
             <p> Estado: 
                <span class="badge badge-{{ $menu->published ? 'success':'danger' }}">
                    {{ $menu->published ? 'Publicada':'No Publicada' }}
                </span>
            </p>
            <div 
                wire:click='toggle_status' 
                class="btn btn-{{ $menu->published ? 'danger':'success' }}"
            >
                {{ $menu->published ? 'Despublicar':'Publicar' }}
            </div>
            <hr>
            <x-admin.delete-btn 
                :key="$menu->id" 
                event="delete_menu"  
                text="Desea eliminar el menu: {{ $menu->title }}"
            />
        </x-admin.card>
    </div>
</div>

resources/views/livewire/admin/menu/form.blade.php
<div class="row">
    <x-admin.input 
        title="Título" 
        model="menu.title" 
        required=true 
        tabindex=1 
        classes="col-md-4" 
        placeholder="Inicio"
    />
    <x-admin.input 
        title="Link (Opcional)" 
        model="menu.link" 
        tabindex=2 
        classes="col-md-8" 
        placeholder="http://google.com"
        :disabled="$menu->pages()->exists()"
        hint="{{ $menu->pages()->exists() ? 'Descativado porque este menu tiene paginas' : false }}"
    />
</div>
<div class="row">
    <x-admin.input 
        title="Posición" 
        model="menu.position" 
        tabindex=3 
        classes="col-md-2" 
        placeholder="10"
    />
    <x-admin.input 
        title="Icono" 
        model="menu.icon" 
        tabindex=4 
        classes="col-md-6"
        placeholder="address-book"
        :disabled="$menu->pages()->exists() || $menu->link"
        hint="{{ $menu->pages()->exists() ? 'Descativado porque este menu tiene paginas' : 'Lista de iconos: https://fontawesome.com/icons?d=gallery&m=free, poner solo el nombre' }}"
    />
    <x-admin.select 
        model="menu.target" 
        title="Abrir en:" 
        :values="$targets" 
        classes="col-md-4" 
        tabindex=5
        :disabled="$menu->pages()->exists()"
        hint="{{ $menu->pages()->exists() ? 'Descativado porque este menu tiene paginas' : false }}"
    />
</div>
<div class="row">
    <x-admin.checkbox 
        title="En el Inicio?" 
        model="menu.to_home" 
        tabindex=5 
        classes="col-md-4"
        :disabled="$menu->pages()->exists() || $menu->link"
        hint="{{ $menu->pages()->exists() ? 'Descativado porque este menu tiene paginas' : false }}"
    />
</div>

resources/views/livewire/admin/menu/list-menu.blade.php
<x-admin.card title="Listado de Menus">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>Titulo</th>
                <th>Posición</th>
                <th>Publicado</th>
                <th>Paginas</th>
                <th>En Inicio?</th>
                <th>Link</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($menus as $menu)
            <tr>
                <td>
                    <a href="{{ route('admin.menu.edit', $menu->id) }}">{{ $menu->title }}</a>
                </td>
                <td>{{ $menu->position }}</td>
                <td>
                    <span class="badge bg-{{ $menu->published ? 'success' : 'danger' }}">
                        {{ $menu->published ? 'Si' : 'No' }}
                    </span>
                </td>
                <td>{{ $menu->pages_count }}</td>
                <td>
                    <span class="badge bg-{{ $menu->to_home ? 'success' : 'danger' }}">
                        {{ $menu->to_home ? 'Si' : 'No' }}
                    </span>
                </td>
                <td>
                    @if($menu->link)
                    {{ $menu->link }}
                    @else
                    <span class="badge bg-secondary"> NO </span>
                    @endif
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="6">
                    <div class="callout callout-info">
                    <p>Todavia No hay Menu</p>
                    </div>
                </td>
            </tr>
            @endforelse
        </tbody>
    </table> 
    <p>
        {{ $menus->links() }}
    </p>
</x-admin.card>

resources/views/livewire/admin/menu/new-menu.blade.php
<div class="row">
    <div class="col-md-9">
        <x-admin.card title="Datos del Menu">
            @include('livewire.admin.menu.form')
        </x-admin.card>
    </div>
    <div class="col-md-3">
        <x-admin.card title="Opciones">
            <x-admin.save-btn event="save_menu" />
        </x-admin.card>
    </div>
</div>